// prisma/seed.ts
import { PrismaClient } from '@prisma/client';
import { PrismaBetterSqlite3 } from '@prisma/adapter-better-sqlite3';

const adapter = new PrismaBetterSqlite3({
  url: process.env.DATABASE_URL || 'file:./dev.db',
});

const prisma = new PrismaClient({ adapter });

async function main() {
  console.log('🌱 Seeding database...');

  // Clear existing voters if you want a clean slate
  await prisma.voter.deleteMany();
  console.log('✅ Cleared existing voters');

  await prisma.voter.createMany({
    data: [
      {
        studentNumber: '2021-00001',
        upEmail: 'cas.juan@up.edu.ph',
        fullName: 'Juan Dela Cruz',
        college: 'CAS',
        department: 'Elektrons',
        program: 'BS Computer Science',
        yearLevel: 4,
        status: 'ENROLLED',
        isEligible: true,
      },
      {
        studentNumber: '2022-00002',
        upEmail: 'cas.maria@up.edu.ph',
        fullName: 'Maria Santos',
        college: 'CAS',
        department: 'Skimmers',
        program: 'BA Political Science',
        yearLevel: 3,
        status: 'ENROLLED',
        isEligible: true,
      },
      {
        studentNumber: '2023-00003',
        upEmail: 'cas.pedro@up.edu.ph',
        fullName: 'Pedro Reyes',
        college: 'CAS',
        department: 'Redbolts',
        program: 'BA History',
        yearLevel: 2,
        status: 'ENROLLED',
        isEligible: true,
      },
      {
        studentNumber: '2021-00004',
        upEmail: 'cas.ana@up.edu.ph',
        fullName: 'Ana Garcia',
        college: 'CAS',
        department: 'Clovers',
        program: 'BS Mathematics',
        yearLevel: 4,
        status: 'ENROLLED',
        isEligible: true,
      },
      {
        studentNumber: '2022-00005',
        upEmail: 'cas.carlos@up.edu.ph',
        fullName: 'Carlos Reyes',
        college: 'CAS',
        department: 'Skimmers',
        program: 'BS Chemistry',
        yearLevel: 3,
        status: 'ENROLLED',
        isEligible: true,
      },
      // ✅ Example: NOT CAS (should be rejected at login)
      {
        studentNumber: '2022-99999',
        upEmail: 'sea.engineer@up.edu.ph',
        fullName: 'Engineering Student',
        college: 'SEA', // NOT CAS
        department: 'Elektrons',
        program: 'BS Chemical Engineering',
        yearLevel: 3,
        status: 'ENROLLED',
        isEligible: true,
      },
      // ✅ Example: LOA (ineligible)
      {
        studentNumber: '2021-00006',
        upEmail: 'loa.student@up.edu.ph',
        fullName: 'LOA Student',
        college: 'CAS',
        department: 'Redbolts',
        program: 'BS Statistics',
        yearLevel: 4,
        status: 'LOA',
        isEligible: false,
      },
      // Additional Elektrons students
      {
        studentNumber: '2023-00007',
        upEmail: 'cas.alex@up.edu.ph',
        fullName: 'Alexandra Torres',
        college: 'CAS',
        department: 'Elektrons',
        program: 'BS Computer Science',
        yearLevel: 2,
        status: 'ENROLLED',
        isEligible: true,
      },
      {
        studentNumber: '2022-00008',
        upEmail: 'cas.miguel@up.edu.ph',
        fullName: 'Miguel Fernandez',
        college: 'CAS',
        department: 'Elektrons',
        program: 'BS Mathematics',
        yearLevel: 3,
        status: 'ENROLLED',
        isEligible: true,
      },
      {
        studentNumber: '2021-00009',
        upEmail: 'cas.isabella@up.edu.ph',
        fullName: 'Isabella Cruz',
        college: 'CAS',
        department: 'Elektrons',
        program: 'BS Computer Science',
        yearLevel: 4,
        status: 'ENROLLED',
        isEligible: true,
      },
      {
        studentNumber: '2024-00010',
        upEmail: 'cas.diego@up.edu.ph',
        fullName: 'Diego Martinez',
        college: 'CAS',
        department: 'Elektrons',
        program: 'BS Chemistry',
        yearLevel: 1,
        status: 'ENROLLED',
        isEligible: true,
      },
      // Additional Redbolts students
      {
        studentNumber: '2023-00011',
        upEmail: 'cas.sophia@up.edu.ph',
        fullName: 'Sophia Rodriguez',
        college: 'CAS',
        department: 'Redbolts',
        program: 'BA Political Science',
        yearLevel: 2,
        status: 'ENROLLED',
        isEligible: true,
      },
      {
        studentNumber: '2022-00012',
        upEmail: 'cas.lucas@up.edu.ph',
        fullName: 'Lucas Kim',
        college: 'CAS',
        department: 'Redbolts',
        program: 'BA History',
        yearLevel: 3,
        status: 'ENROLLED',
        isEligible: true,
      },
      {
        studentNumber: '2021-00013',
        upEmail: 'cas.emma@up.edu.ph',
        fullName: 'Emma Watson',
        college: 'CAS',
        department: 'Redbolts',
        program: 'BA Political Science',
        yearLevel: 4,
        status: 'ENROLLED',
        isEligible: true,
      },
      {
        studentNumber: '2024-00014',
        upEmail: 'cas.oliver@up.edu.ph',
        fullName: 'Oliver Tan',
        college: 'CAS',
        department: 'Redbolts',
        program: 'BA History',
        yearLevel: 1,
        status: 'ENROLLED',
        isEligible: true,
      },
      // Additional Skimmers students
      {
        studentNumber: '2023-00015',
        upEmail: 'cas.amelia@up.edu.ph',
        fullName: 'Amelia Chen',
        college: 'CAS',
        department: 'Skimmers',
        program: 'BS Biology',
        yearLevel: 2,
        status: 'ENROLLED',
        isEligible: true,
      },
      {
        studentNumber: '2022-00016',
        upEmail: 'cas.james@up.edu.ph',
        fullName: 'James Wilson',
        college: 'CAS',
        department: 'Skimmers',
        program: 'BS Chemistry',
        yearLevel: 3,
        status: 'ENROLLED',
        isEligible: true,
      },
      {
        studentNumber: '2021-00017',
        upEmail: 'cas.charlotte@up.edu.ph',
        fullName: 'Charlotte Brown',
        college: 'CAS',
        department: 'Skimmers',
        program: 'BS Biology',
        yearLevel: 4,
        status: 'ENROLLED',
        isEligible: true,
      },
      {
        studentNumber: '2024-00018',
        upEmail: 'cas.noah@up.edu.ph',
        fullName: 'Noah Lee',
        college: 'CAS',
        department: 'Skimmers',
        program: 'BS Chemistry',
        yearLevel: 1,
        status: 'ENROLLED',
        isEligible: true,
      },
      // Additional Clovers students
      {
        studentNumber: '2023-00019',
        upEmail: 'cas.mia@up.edu.ph',
        fullName: 'Mia Anderson',
        college: 'CAS',
        department: 'Clovers',
        program: 'BS Mathematics',
        yearLevel: 2,
        status: 'ENROLLED',
        isEligible: true,
      },
      {
        studentNumber: '2022-00020',
        upEmail: 'cas.william@up.edu.ph',
        fullName: 'William Thompson',
        college: 'CAS',
        department: 'Clovers',
        program: 'BS Statistics',
        yearLevel: 3,
        status: 'ENROLLED',
        isEligible: true,
      },
      {
        studentNumber: '2021-00021',
        upEmail: 'cas.harper@up.edu.ph',
        fullName: 'Harper Davis',
        college: 'CAS',
        department: 'Clovers',
        program: 'BS Mathematics',
        yearLevel: 4,
        status: 'ENROLLED',
        isEligible: true,
      },
      {
        studentNumber: '2024-00022',
        upEmail: 'cas.ethan@up.edu.ph',
        fullName: 'Ethan Garcia',
        college: 'CAS',
        department: 'Clovers',
        program: 'BS Statistics',
        yearLevel: 1,
        status: 'ENROLLED',
        isEligible: true,
      },
      // More Elektrons students
      {
        studentNumber: '2023-00023',
        upEmail: 'cas.luna@up.edu.ph',
        fullName: 'Luna Park',
        college: 'CAS',
        department: 'Elektrons',
        program: 'BS Computer Science',
        yearLevel: 2,
        status: 'ENROLLED',
        isEligible: true,
      },
      {
        studentNumber: '2022-00024',
        upEmail: 'cas.henry@up.edu.ph',
        fullName: 'Henry White',
        college: 'CAS',
        department: 'Elektrons',
        program: 'BS Mathematics',
        yearLevel: 3,
        status: 'ENROLLED',
        isEligible: true,
      },
      // More Redbolts students
      {
        studentNumber: '2023-00025',
        upEmail: 'cas.ava@up.edu.ph',
        fullName: 'Ava Johnson',
        college: 'CAS',
        department: 'Redbolts',
        program: 'BA Political Science',
        yearLevel: 2,
        status: 'ENROLLED',
        isEligible: true,
      },
      {
        studentNumber: '2022-00026',
        upEmail: 'cas.mason@up.edu.ph',
        fullName: 'Mason Harris',
        college: 'CAS',
        department: 'Redbolts',
        program: 'BA History',
        yearLevel: 3,
        status: 'ENROLLED',
        isEligible: true,
      },
      // More Skimmers students
      {
        studentNumber: '2023-00027',
        upEmail: 'cas.evelyn@up.edu.ph',
        fullName: 'Evelyn Clark',
        college: 'CAS',
        department: 'Skimmers',
        program: 'BS Biology',
        yearLevel: 2,
        status: 'ENROLLED',
        isEligible: true,
      },
      {
        studentNumber: '2022-00028',
        upEmail: 'cas.logan@up.edu.ph',
        fullName: 'Logan Lewis',
        college: 'CAS',
        department: 'Skimmers',
        program: 'BS Chemistry',
        yearLevel: 3,
        status: 'ENROLLED',
        isEligible: true,
      },
      // More Clovers students
      {
        studentNumber: '2023-00029',
        upEmail: 'cas.grace@up.edu.ph',
        fullName: 'Grace Walker',
        college: 'CAS',
        department: 'Clovers',
        program: 'BS Mathematics',
        yearLevel: 2,
        status: 'ENROLLED',
        isEligible: true,
      },
      {
        studentNumber: '2022-00030',
        upEmail: 'cas.jackson@up.edu.ph',
        fullName: 'Jackson Hall',
        college: 'CAS',
        department: 'Clovers',
        program: 'BS Statistics',
        yearLevel: 3,
        status: 'ENROLLED',
        isEligible: true,
      },
    ],
  });

  console.log('✅ Seeded dummy voters');
}

main()
  .catch((e) => {
    console.error('❌ Error seeding:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

